### ISSUE TITLE
Download ScanNet-GSReg

### ISSUE THREAD

**Issue by SongJiang-WHU** [GAP-LAB-CUHK-SZ/GaussReg#2]
I always fail to download ScanNet-GSReg dataset due to various problems, do you have your data saved in Baidu.com disk, can you share your Baidu.com disk? Or can you provide me with other download methods?

**Comment by Jiahao620** [comment]
Actually, the problem you mentioned does exist, so I split the large compressed package into many small compressed packages. I suggest you download a part at a time, such as downloading 20 small compressed packages each time.

**Comment by Beining1** [comment]
I also have the same question. Can you provide a tiny dataset later?

**Comment by Jiahao620** [comment]
I have released a sample case here:https://onedrive.live.com/?id=31078419AB45666E%21s397f1825b1284f1abf6ce1bb7f242dbc&cid=31078419AB45666E.
Is it enough for you?
![image](https://github.com/user-attachments/assets/16287eaa-2858-43ad-b7f5-efd4f8de7f6a)

**Comment by Beining1** [comment]
> I have released a sample case here:https://onedrive.live.com/?id=31078419AB45666E%21s397f1825b1284f1abf6ce1bb7f242dbc&cid=31078419AB45666E. Is it enough for you? ![image](https://private-user-images.githubusercontent.com/92793267/376543125-16287eaa-2858-43ad-b7f5-efd4f8de7f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTQ3NDAsIm5iZiI6MTcyOTA1NDQ0MCwicGF0aCI6Ii85Mjc5MzI2Ny8zNzY1NDMxMjUtMTYyODdlYWEtMjg1OC00M2FkLWI3ZjUtZWZkNGY4ZGU3ZjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA0NTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGIwZTg0NzJiNGIzYjk3ZmQ3MWUyYTEwZDZmOGY0NDJlZDc2NDlmNDFlYmNmOTRkMTNiZTdjODgxODFiOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TcwoHFWDvdglx2dOv98K4-yxVFKZ1MkLD5c5uatNfk8)

​In Chinese mainland ，I can't open the onedrive share link directly. Although I used a VPN, I still can't open the file you shared, 
<img width="960" alt="8d5f76d92665b477f3d58013563522a" src="https://github.com/user-attachments/assets/08899996-0dd2-437b-9020-fac6a600b9b7">
I think you may need to change the permissions so that anyone can access it. Or can you share the data set via Baidu or Google Cloud Disk?

**Comment by Jiahao620** [comment]
Maybe you should try another VPN？I requested my friends in Chinese mainland to download this data through their VPN and they succeeded. Has anyone else encountered this problem?

**Comment by SongJiang-WHU** [comment]
> Maybe you should try another VPN？I requested my friends in Chinese mainland to download this data through their VPN and they succeeded. Has anyone else encountered this problem?

Maybe it's not a VPN issue. I tried many times but failed to download, even though I only downloaded 5 chunks

**Comment by Jiahao620** [comment]
I share the data set via Baidu Cloud Disk: https://pan.baidu.com/s/101wdzP3ETx1JVVLN9FrZQg?pwd=tq39

**Comment by SongJiang-WHU** [comment]
Can you share the Baidu.com disk address of the ScanNet-GSReg dataset? Not the example data fitness. the download method through the current share is always interrupted causing the download to fail.

**Comment by Jiahao620** [comment]
I tried to upload the ScanNet-GSReg dataset to the Baidu.com disk. However, this resulted in a lot of data missing. So I gave up uploading to Baidu Cloud Disk.

**Comment by SeungGyu-Song** [comment]
Hello!
First of all, thanks a lot for your hard work! 
I am very enthusiastic to try running a demo as written in the ReadMe, but unfortunately OneDrive page does not work :/
Could you please renew the page or let me know how to get the dataset? 
I am sorry that I do not have an ID for Baidunetdistk.  

Thank you once again for your interesting work!

Happy New Year! 
Best, 
Seunggyu
